import preloader from 'spectacle/lib/utils/preloader';

const images = {
  crop: require('assets/iconmonstr-crop-10.svg'),
  ruler19: require('assets/iconmonstr-ruler-19.svg'),
  ruler25: require('assets/iconmonstr-ruler-25.svg'),
  ruler26: require('assets/iconmonstr-ruler-26.svg'),
  ruler32: require('assets/iconmonstr-ruler-32.svg'),
  parrot: require('assets/parrots/hd/parrot.gif'),
  colouredSucculents: require('assets/andrew-phillips-22549.jpg'),
  winkervsbecks: require('assets/winkervsbecks.jpg'),
  gems: require('assets/gems.gif'),
  shadow: require('assets/shadow.gif'),
  glossy: require('assets/glossy.gif'),
  chrome: require('assets/chrome.gif'),
  card: require('assets/card.gif'),
  someWords: require('assets/some-words.gif'),
  uber: require('assets/uber.gif'),
  manypolygons: require('assets/manypolygons.gif'),
  toggle: require('assets/toggle.svg'),
  knob: require('assets/knob.svg'),
  slider: require('assets/slider.svg'),
  splash: require('assets/splash.gif'),
  swimmer: require('assets/swimmer.gif'),
  hexagon: require('assets/beesandbombs/hexagon.gif'),
  boxes: require('assets/beesandbombs/boxes.gif'),
  out: require('assets/beesandbombs/out.gif'),
  bouncers: require('assets/beesandbombs/bouncers.gif'),
  dotLineWave: require('assets/beesandbombs/dot-line-wave.gif'),
  blob: require('assets/beesandbombs/blob.gif'),
  friendlyBlocks: require('assets/beesandbombs/friendly-blocks.gif'),
  waveD: require('assets/beesandbombs/wave_d.gif'),
  cubewave: require('assets/beesandbombs/cubewave.gif'),
  weaves: require('assets/beesandbombs/weaves.gif'),
  bubbles2: require('assets/beesandbombs/bubbles2.gif'),
  spins: require('assets/beesandbombs/spins.gif'),
  spiralbig: require('assets/beesandbombs/spiralbig.gif'),
  spiraldots: require('assets/beesandbombs/spiraldots.gif'),
  netmag: require('assets/netmag.gif'),
  lever: require('assets/lever.gif'),
  cactus: require('assets/annie-spratt-79272.jpg'),
  gemsExplain: require('assets/gems-explain.jpg'),
  splashExplain: require('assets/splash-explain.jpg'),
  octagon: require('assets/octagon.jpg'),
  polar: require('assets/polar.jpg'),
  cartesian: require('assets/cartesian.jpg'),
  measure: require('assets/measure.jpg'),
  sorcery: require('assets/sorcery.gif'),
  codepen: require('assets/codepen.png'),
  topography: require('assets/topography.gif'),
  paths: require('assets/paths.gif'),
  napoleonTheorem: require('assets/work/napoleon-theorem.gif'),
  reactiveO: require('assets/work/reactive-o.gif'),
  triangleninja: require('assets/work/triangleninja.gif'),
  truncation: require('assets/work/truncation.gif'),
  chillwave: require('assets/work/chillwave-alt.gif'),
  touchId: require('assets/work/touch-id.gif'),
  core: require('assets/work/core.gif'),
  pizzaTheorem: require('assets/work/pizza-theorem.gif'),
  oam: require('assets/work/oam-alt.gif'),
  generativeGestaltung1: require('assets/generative-gestaltung-1.jpg'),
  generativeGestaltung2: require('assets/generative-gestaltung-2.jpg'),
  generativeGestaltung3: require('assets/generative-gestaltung-3.png'),
};

preloader(images);

export default images;
